### PR TITLE
Allowing ndir = 0

### PR DESCRIPTION
**Pull request by jlconlin**
This should resolve issue #17 \.

### CODE REVIEW

**Comment by jlconlin** [comment]
I've confirmed that the tests that I changed pass. I'm still compiling the rest. (It takes a long time.) Will let you know when everything passes.

**Comment by nathangibson14** [comment]
Looks good to me.  Thanks for getting to it before I did :smile:

Let me know when the tests pass, then I'll approve.

**Comment by jlconlin** [comment]
I had to push up one more commit. I was a little surprised that `#include <experimental/optional>` was still in a few tests. Those should have been removed when we moved to C++17.

Anyway, all tests now pass—if you trust me.

**Comment by nathangibson14** [comment]
I tried to build the tests, and one didn't compile for me.  Let me look into what's going on.

**Comment by nathangibson14** [comment]
LEAPR.Card6 gives me compiler errors on GCC 8.3.0 on Snow, something related to ranges.  Everything else compiles and passes.  I can check on another platform/compiler, but can you see if you get the same behavior?

**Comment by nathangibson14** [comment]
It works on GCC 9.2.0 on my Mac.  So now the big question... is GCC 8.3.0 or Snow the problem?  I think I failed at the scientific method so far.

**Comment by jlconlin** [comment]
> It works on GCC 9.2.0 on my Mac. So now the big question... is GCC 8.3.0 or Snow the problem? I think I failed at the scientific method so far.

It's hard to tell. I tried to compile on Snow with GCC 8.3.0 and got a different set of errors than you did. Grrrr. It's frustrating.

**Comment by nathangibson14** [comment]
I was able to compile and run everything successfully on Snow with GCC 7.4.0.  I tried again from a clean slate with GCC 8.3.0 on Snow, and I again crashed on `LEAPR.Card6.test`.  This doesn't make a ton of sense, not sure how to proceed.  I'm leaning toward not worrying about this, as it seems like a relatively system-dependent issue, isn't related to this PR, and isn't of much consequence regardless.

**Pull request merged**
